_target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
_partial_: true
T_0: 100 # Number of iterations until the first restart.
T_mult: 0.9 #A factor by which T_i increases after a restart. Default: 1.
eta_min: 4e-5 # Minimum learning rate. Default: 0
