_target_: torch.optim.lr_scheduler.OneCycleLR
_partial_: true
max_lr: 2e-2
total_steps: null
epochs: ${trainer.max_epochs} # Dynamically set T_max to total epochs
steps_per_epoch: 1
pct_start: 0.3
anneal_strategy: "cos"
cycle_momentum: true
base_momentum: 0.85
max_momentum: 0.95
div_factor: 25.0
final_div_factor: 10000.0
three_phase: False
last_epoch: -1
