FROM sailugr/sinergym:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    fzf \
    luarocks \
    cargo \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install neovim

# Install Node.js (npm comes with it)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*
# Download and install latest Neovim (correct filename)
RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
    && tar xzvf nvim-linux-x86_64.tar.gz \
    && mv nvim-linux-x86_64 /opt/nvim \
    && ln -s /opt/nvim/bin/nvim /usr/local/bin/nvim \
    && rm nvim-linux-x86_64.tar.gz


# Create directory and debugpy virtual environment with Python 3.12
RUN mkdir -p /root/.pyenv/versions \
    && python3 -m venv /root/.pyenv/versions/debugpy-3.11 \
    && /root/.pyenv/versions/debugpy-3.11/bin/pip install --upgrade pip debugpy

# Verify
RUN nvim --version && node --version && npm --version \
    && /root/.pyenv/versions/debugpy-3.11/bin/python --version

RUN git clone https://github.com/l2late/nvim-config.git /root/.config/nvim
WORKDIR /workspaces/sinergym
