homogeneous_edges_first_floor = [
    # ENCLOSEDOFFICE_BOT_1
    ("ENCLOSEDOFFICE_BOT_1", "CONFROOM_BOT_1"),
    ("ENCLOSEDOFFICE_BOT_1", "LOUNGE_BOT"),
    ("ENCLOSEDOFFICE_BOT_1", "CORRIDOR_BOT_1"),
    ("ENCLOSEDOFFICE_BOT_1", "CORRIDOR_BOT_2"),
    # CONFROOM_BOT_1
    ("CONFROOM_BOT_1", "ENCLOSEDOFFICE_BOT_1"),
    ("CONFROOM_BOT_1", "ENCLOSEDOFFICE_BOT_3"),
    ("CONFROOM_BOT_1", "CORRIDOR_BOT_1"),
    # ENCLOSEDOFFICE_BOT_3
    ("ENCLOSEDOFFICE_BOT_3", "CONFROOM_BOT_1"),
    ("ENCLOSEDOFFICE_BOT_3", "LOUNGE_BOT"),
    ("ENCLOSEDOFFICE_BOT_3", "CORRIDOR_BOT_1"),
    # LOUNGE_BOT
    ("LOUNGE_BOT", "ENCLOSEDOFFICE_BOT_3"),
    ("LOUNGE_BOT", "ENCLOSEDOFFICE_BOT_4"),
    ("LOUNGE_BOT", "CORRIDOR_BOT_1"),
    # ENCLOSEDOFFICE_BOT_4
    ("ENCLOSEDOFFICE_BOT_4", "LOUNGE_BOT"),
    ("ENCLOSEDOFFICE_BOT_4", "CONFROOM_BOT_2"),
    ("ENCLOSEDOFFICE_BOT_4", "CORRIDOR_BOT_1"),
    # CONFROOM_BOT_2
    ("CONFROOM_BOT_2", "ENCLOSEDOFFICE_BOT_4"),
    ("CONFROOM_BOT_2", "ENCLOSEDOFFICE_BOT_2"),
    ("CONFROOM_BOT_2", "CORRIDOR_BOT_1"),
    # ENCLOSEDOFFICE_BOT_2
    ("ENCLOSEDOFFICE_BOT_2", "CONFROOM_BOT_2"),
    ("ENCLOSEDOFFICE_BOT_2", "CORRIDOR_BOT_1"),
    ("ENCLOSEDOFFICE_BOT_2", "CORRIDOR_BOT_2"),
    ("ENCLOSEDOFFICE_BOT_2", "OPENOFFICE_BOT_3"),
    # OPENOFFICE_BOT_3
    ("OPENOFFICE_BOT_3", "ENCLOSEDOFFICE_BOT_2"),
    ("OPENOFFICE_BOT_3", "CORRIDOR_BOT_2"),
    ("OPENOFFICE_BOT_3", "CLASSROOM_BOT"),
    # CLASSROOM_BOT
    ("CLASSROOM_BOT", "OPENOFFICE_BOT_3"),
    ("CLASSROOM_BOT", "CORRIDOR_BOT_2"),
    ("CLASSROOM_BOT", "ENCLOSEDOFFICE_BOT_1"),
    # OPENOFFICE_BOT_1
    ("OPENOFFICE_BOT_1", "ACTIVESTORAGE_BOT_1"),
    ("OPENOFFICE_BOT_1", "ACTIVESTORAGE_BOT_4"),
    ("OPENOFFICE_BOT_1", "STAIR_BOT_1"),
    ("OPENOFFICE_BOT_1", "CORRIDOR_BOT_1"),
    ("OPENOFFICE_BOT_1", "CORRIDOR_BOT_2"),
    # ACTIVESTORAGE_BOT_1
    ("ACTIVESTORAGE_BOT_1", "OPENOFFICE_BOT_1"),
    ("ACTIVESTORAGE_BOT_1", "STAIR_BOT_1"),
    ("ACTIVESTORAGE_BOT_1", "LOBBY_BOT"),
    ("ACTIVESTORAGE_BOT_1", "CORRIDOR_BOT_1"),
    # STAIR_BOT_1
    ("STAIR_BOT_1", "ACTIVESTORAGE_BOT_1"),
    ("STAIR_BOT_1", "OPENOFFICE_BOT_1"),
    ("STAIR_BOT_1", "RESTROOM_BOT"),
    ("STAIR_BOT_1", "ACTIVESTORAGE_BOT_4"),
    # ACTIVESTORAGE_BOT_4
    ("ACTIVESTORAGE_BOT_4", "STAIR_BOT_1"),
    ("ACTIVESTORAGE_BOT_4", "OPENOFFICE_BOT_1"),
    ("ACTIVESTORAGE_BOT_4", "DINING_BOT"),
    ("ACTIVESTORAGE_BOT_4", "CORRIDOR_BOT_2"),
    # RESTROOM_BOT
    ("RESTROOM_BOT", "ACTIVESTORAGE_BOT_4"),
    ("RESTROOM_BOT", "STAIR_BOT_1"),
    ("RESTROOM_BOT", "LOBBY_BOT"),
    ("RESTROOM_BOT", "ACTIVESTORAGE_BOT_1"),
    # DINING_BOT
    ("DINING_BOT", "ACTIVESTORAGE_BOT_4"),
    ("DINING_BOT", "CORRIDOR_BOT_2"),
    ("DINING_BOT", "LOBBY_BOT"),
    ("DINING_BOT", "RESTROOM_BOT"),
    # LOBBY_BOT
    ("LOBBY_BOT", "ACTIVESTORAGE_BOT_1"),
    ("LOBBY_BOT", "RESTROOM_BOT"),
    ("LOBBY_BOT", "DINING_BOT"),
    ("LOBBY_BOT", "ACTIVESTORAGE_BOT_2"),
    ("LOBBY_BOT", "MECHANICAL_BOT"),
    ("LOBBY_BOT", "ACTIVESTORAGE_BOT_3"),
    ("LOBBY_BOT", "CORRIDOR_BOT_1"),
    ("LOBBY_BOT", "CORRIDOR_BOT_2"),
    # ACTIVESTORAGE_BOT_2
    ("ACTIVESTORAGE_BOT_2", "LOBBY_BOT"),
    ("ACTIVESTORAGE_BOT_2", "MECHANICAL_BOT"),
    ("ACTIVESTORAGE_BOT_2", "OPENOFFICE_BOT_2"),
    ("ACTIVESTORAGE_BOT_2", "CORRIDOR_BOT_1"),
    ("ACTIVESTORAGE_BOT_2", "STAIR_BOT_2"),
    # MECHANICAL_BOT
    ("MECHANICAL_BOT", "LOBBY_BOT"),
    ("MECHANICAL_BOT", "ACTIVESTORAGE_BOT_2"),
    ("MECHANICAL_BOT", "STAIR_BOT_2"),
    ("MECHANICAL_BOT", "ACTIVESTORAGE_BOT_3"),
    # ACTIVESTORAGE_BOT_3
    ("ACTIVESTORAGE_BOT_3", "MECHANICAL_BOT"),
    ("ACTIVESTORAGE_BOT_3", "STAIR_BOT_2"),
    ("ACTIVESTORAGE_BOT_3", "CORRIDOR_BOT_2"),
    ("ACTIVESTORAGE_BOT_3", "LOBBY_BOT"),
    ("ACTIVESTORAGE_BOT_3", "OPENOFFICE_BOT_2"),
    # STAIR_BOT_2
    ("STAIR_BOT_2", "ACTIVESTORAGE_BOT_3"),
    ("STAIR_BOT_2", "MECHANICAL_BOT"),
    ("STAIR_BOT_2", "ACTIVESTORAGE_BOT_2"),
    ("STAIR_BOT_2", "OPENOFFICE_BOT_2"),
    # OPENOFFICE_BOT_2
    ("OPENOFFICE_BOT_2", "STAIR_BOT_2"),
    ("OPENOFFICE_BOT_2", "ACTIVESTORAGE_BOT_2"),
    ("OPENOFFICE_BOT_2", "ACTIVESTORAGE_BOT_3"),
    ("OPENOFFICE_BOT_2", "CORRIDOR_BOT_1"),
    ("OPENOFFICE_BOT_2", "CORRIDOR_BOT_2"),
    # CORRIDOR_BOT_1
    ("CORRIDOR_BOT_1", "ENCLOSEDOFFICE_BOT_1"),
    ("CORRIDOR_BOT_1", "CONFROOM_BOT_1"),
    ("CORRIDOR_BOT_1", "ENCLOSEDOFFICE_BOT_3"),
    ("CORRIDOR_BOT_1", "LOUNGE_BOT"),
    ("CORRIDOR_BOT_1", "ENCLOSEDOFFICE_BOT_4"),
    ("CORRIDOR_BOT_1", "CONFROOM_BOT_2"),
    ("CORRIDOR_BOT_1", "ENCLOSEDOFFICE_BOT_2"),
    ("CORRIDOR_BOT_1", "OPENOFFICE_BOT_1"),
    ("CORRIDOR_BOT_1", "ACTIVESTORAGE_BOT_1"),
    ("CORRIDOR_BOT_1", "LOBBY_BOT"),
    ("CORRIDOR_BOT_1", "ACTIVESTORAGE_BOT_2"),
    ("CORRIDOR_BOT_1", "OPENOFFICE_BOT_2"),
    # CORRIDOR_BOT_2
    ("CORRIDOR_BOT_2", "ENCLOSEDOFFICE_BOT_1"),
    ("CORRIDOR_BOT_2", "CLASSROOM_BOT"),
    ("CORRIDOR_BOT_2", "OPENOFFICE_BOT_3"),
    ("CORRIDOR_BOT_2", "ENCLOSEDOFFICE_BOT_2"),
    ("CORRIDOR_BOT_2", "OPENOFFICE_BOT_1"),
    ("CORRIDOR_BOT_2", "ACTIVESTORAGE_BOT_4"),
    ("CORRIDOR_BOT_2", "DINING_BOT"),
    ("CORRIDOR_BOT_2", "LOBBY_BOT"),
    ("CORRIDOR_BOT_2", "ACTIVESTORAGE_BOT_3"),
    ("CORRIDOR_BOT_2", "OPENOFFICE_BOT_2"),
]

external_connected_nodes = [
    "CONFROOM_BOT_1",
    "ENCLOSEDOFFICE_BOT_3",
    "LOUNGE_BOT",
    "ENCLOSEDOFFICE_BOT_4",
    "CONFROOM_BOT_2",
    "ENCLOSEDOFFICE_BOT_2",
    "OPENOFFICE_BOT_3",
    "CLASSROOM_BOT",
    "OPENOFFICE_BOT_1",
]

# Create list of tuples so each node in external_connected_nodes is connected to 'external_node_name'
external_node_name = "Environment"

external_edges_first_floor = [
    (node, external_node_name) for node in external_connected_nodes
]

heterogeneous_edges_first_floor = (
    homogeneous_edges_first_floor + external_edges_first_floor
)
