defaults:
  - default_schema

_target_: alphabuilding.infrastructure.lightning.datamodules.brcm_datamodule.BRCMTrajectoryLitDataModule
# csv_file: "/home/l2late/stack/Master/Thesis/master-thesis-code/alpha_building_model/tests/data/matlab_brcm_simulation_results/five_room_building_simulation_results.csv"
csv_file: "${paths.data_dir}/brcm_simulation_results/hysteresis_prbs/five_room_1_year_Ts_0.25_hysteresis-random_Tmargin_2_real.csv"
size: null
window_size: ${window_size}
initial_horizon: ${horizon}
max_horizon: ${horizon}
num_workers: 0
batch_size: 128
train_ratio: 0.1
val_ratio: 0.05
noise_stds: [0.0, 0.0]
